// Atelier Kern — démo data
// 3 teintes tertiaires pour thumbnails, en rotation
const TINTS = ['#2E4E3E', '#3A3020', '#1E2830'];

const CATEGORIES = [
  { id: 'all', label: 'Tout' },
  { id: 'signature', label: 'Signature' },
  { id: 'tarte', label: 'Tartes' },
  { id: 'choco', label: 'Chocolat' },
  { id: 'viennoi', label: 'Viennoiserie' },
  { id: 'saison', label: 'Saison' },
];

const PRODUCTS = [
  {
    id: 'p1',
    name: 'Tarte Praliné',
    cat: 'tarte',
    catLabel: 'Tarte',
    price: 7.80,
    tag: 'Signature',
    short: 'Praliné noisette du Piémont, sablé breton, ganache Valrhona 66%.',
    detail: 'Sablé pur beurre, ganache Caraïbe 66%, praliné noisette grillée 52%, noisettes torréfiées. Pièce de 110g.',
    shape: 'tall',
  },
  {
    id: 'p2',
    name: 'Paris-Brest',
    cat: 'signature',
    catLabel: 'Pâte à choux',
    price: 6.50,
    tag: 'Classique',
    short: 'Praliné crémeux, pâte à choux craquelée, noisettes torréfiées.',
    detail: 'Praliné maison noisette-amande torréfié 24h, crème pâtissière vanille Madagascar, craquelin cassonade.',
    shape: 'normal',
  },
  {
    id: 'p3',
    name: 'Kouign-amann',
    cat: 'viennoi',
    catLabel: 'Viennoiserie',
    price: 4.20,
    tag: 'Limité',
    short: 'Pâte feuilletée levée, beurre AOP, sucre caramélisé.',
    detail: 'Pétrissage lent 72h, beurre de baratte AOP, caramel blond à la fleur de sel de Guérande. Cuisson du matin.',
    shape: 'normal',
  },
  {
    id: 'p4',
    name: 'Millefeuille Vanille',
    cat: 'signature',
    catLabel: 'Feuilletage',
    price: 7.20,
    tag: null,
    short: 'Feuilletage inversé, crème diplomate, vanille Bourbon.',
    detail: 'Pâte feuilletée inversée, crème diplomate vanille Bourbon, caramélisation sucre glace. Montage minute.',
    shape: 'wide',
  },
  {
    id: 'p5',
    name: 'Fondant Noir 70%',
    cat: 'choco',
    catLabel: 'Chocolat',
    price: 6.90,
    tag: null,
    short: 'Ganache Tanzanie 70%, biscuit cuillère, fleur de sel.',
    detail: 'Tanzanie 70% origine unique, biscuit cuillère, fleur de sel Guérande. Texture fondante, centre coulant.',
    shape: 'normal',
  },
  {
    id: 'p6',
    name: 'Croissant',
    cat: 'viennoi',
    catLabel: 'Viennoiserie',
    price: 2.40,
    tag: null,
    short: 'Beurre AOP Charentes-Poitou, fermentation 36h.',
    detail: 'Farine T45 française, beurre AOP Charentes-Poitou 82%, pointage long 36h.',
    shape: 'tall',
  },
  {
    id: 'p7',
    name: 'Tarte Citron Basilic',
    cat: 'tarte',
    catLabel: 'Tarte',
    price: 6.80,
    tag: 'Saison',
    short: 'Citron de Menton, meringue italienne, sablé basilic.',
    detail: 'Crème citron de Menton confite, meringue italienne légèrement brûlée, sablé infusé basilic frais.',
    shape: 'normal',
  },
  {
    id: 'p8',
    name: 'Éclair Café',
    cat: 'signature',
    catLabel: 'Pâte à choux',
    price: 5.40,
    tag: null,
    short: 'Crème pâtissière café, glaçage fondant, grains torréfiés.',
    detail: 'Café Arabica Éthiopie Yirgacheffe, crème pâtissière infusée à froid 12h, fondant maison.',
    shape: 'normal',
  },
  {
    id: 'p9',
    name: 'Baba au Rhum',
    cat: 'signature',
    catLabel: 'Pâte levée',
    price: 6.20,
    tag: null,
    short: 'Brioche imbibée, rhum agricole Martinique, Chantilly vanille.',
    detail: 'Pâte à baba levée, imbibage rhum agricole AOC Martinique, Chantilly vanille Madagascar fouettée minute.',
    shape: 'wide',
  },
];

const VALEURS = [
  { n: '01', title: 'Matières vivantes', body: 'Farine T45 meulée sur pierre, beurre AOP de baratte, chocolat origine unique. On choisit les ingrédients comme on choisit ses mots.' },
  { n: '02', title: 'Temps long', body: 'Fermentations de 36 à 72 heures. Pas de raccourcis, pas d\'additifs. Ce qui prend du temps en prend.' },
  { n: '03', title: 'Production du jour', body: 'Tout sort des fours le matin. Rien n\'est congelé, rien n\'est conservé. Ce qui reste le soir est donné.' },
  { n: '04', title: 'Circuit court', body: 'Producteurs belges et français uniquement. Distance maximale: 600 km. Traçabilité totale sur demande.' },
];

window.AK_DATA = { TINTS, CATEGORIES, PRODUCTS, VALEURS };
