// data.jsx — products, navigation, static content for Maison Dorée

const CATEGORIES = [
  { id: 'all', label: 'Tout' },
  { id: 'signatures', label: 'Signatures' },
  { id: 'tartes', label: 'Tartes' },
  { id: 'entremets', label: 'Entremets' },
  { id: 'viennoiseries', label: 'Viennoiseries' },
  { id: 'chocolats', label: 'Chocolats' },
];

// 14 products with layout pattern driving the asymmetric grid.
// Layout pattern (per charte): tall | normal / wide / normal | normal, looped.
const PRODUCTS = [
  {
    id: 'p1', name: 'Obsidienne', cat: 'signatures', catLabel: 'Signature',
    price: 14, tag: 'Nouveau', layout: 'tall',
    bg: '#1C1814', mono: 'O',
    desc: 'Biscuit chocolat 70%, cerises griottes, chantilly vanille de Madagascar.',
    allergens: 'Gluten · Lait · Œuf',
    origin: 'Madagascar',
    time: '24h',
  },
  {
    id: 'p2', name: 'Sicilienne', cat: 'tartes', catLabel: 'Tarte',
    price: 9.5, layout: 'normal',
    bg: '#2A2318', mono: 'S',
    desc: 'Pâte sablée, crème citron de Sicile, meringue italienne dorée.',
    allergens: 'Gluten · Œuf',
    origin: 'Sicile',
    time: '12h',
  },
  {
    id: 'p3', name: 'Mille-feuille Maison', cat: 'signatures', catLabel: 'Signature',
    price: 8.5, layout: 'wide', tag: 'Exclusif',
    bg: '#242018', mono: 'M',
    desc: 'Feuilletage inversé, crème diplomate vanille de Tahiti, caramélisation au sucre muscovado.',
    allergens: 'Gluten · Lait · Œuf',
    origin: 'Tahiti',
    time: '48h',
  },
  {
    id: 'p4', name: 'Praline', cat: 'entremets', catLabel: 'Entremet',
    price: 11, layout: 'normal',
    bg: '#1F1A14', mono: 'P',
    desc: 'Dacquoise noisette, praliné maison, mousse chocolat au lait.',
    allergens: 'Fruits à coque · Lait · Œuf',
    origin: 'Piémont',
    time: '24h',
  },
  {
    id: 'p5', name: 'Cédrat', cat: 'entremets', catLabel: 'Entremet',
    price: 10.5, layout: 'normal',
    bg: '#2C2518', mono: 'C',
    desc: 'Confit de cédrat de Corse, crémeux yuzu, biscuit amande.',
    allergens: 'Gluten · Fruits à coque · Œuf',
    origin: 'Corse',
    time: '24h',
  },
  {
    id: 'p6', name: 'Paris-Bruxelles', cat: 'signatures', catLabel: 'Signature',
    price: 7.5, layout: 'tall', tag: 'Saison',
    bg: '#1A1612', mono: 'PB',
    desc: 'Pâte à choux croustillante, praliné amande-noisette torréfié maison.',
    allergens: 'Gluten · Fruits à coque · Lait · Œuf',
    origin: 'Bruxelles',
    time: '18h',
  },
  {
    id: 'p7', name: 'Figue Noire', cat: 'tartes', catLabel: 'Tarte',
    price: 9, layout: 'normal',
    bg: '#221C17', mono: 'F',
    desc: 'Sablé breton, confit de figue noire de Solliès, mascarpone infusé thym.',
    allergens: 'Gluten · Lait · Œuf',
    origin: 'Provence',
    time: '12h',
  },
  {
    id: 'p8', name: 'Noir Absolu', cat: 'chocolats', catLabel: 'Chocolat',
    price: 12, layout: 'wide',
    bg: '#14110D', mono: 'NA',
    desc: 'Ganache chocolat Pérou 80%, fève de Tonka, sablé cacao.',
    allergens: 'Gluten · Lait',
    origin: 'Pérou',
    time: '36h',
  },
  {
    id: 'p9', name: 'Kouign', cat: 'viennoiseries', catLabel: 'Viennoiserie',
    price: 5.5, layout: 'normal',
    bg: '#2D2618', mono: 'K',
    desc: 'Pâte feuilletée au beurre demi-sel, sucre caramélisé.',
    allergens: 'Gluten · Lait',
    origin: 'Bretagne',
    time: '8h',
  },
  {
    id: 'p10', name: 'Rosalie', cat: 'entremets', catLabel: 'Entremet',
    price: 10, layout: 'normal',
    bg: '#251C1A', mono: 'R',
    desc: 'Mousse rose de Damas, cœur litchi, biscuit pistache.',
    allergens: 'Gluten · Fruits à coque · Lait · Œuf',
    origin: 'Damas',
    time: '24h',
  },
  {
    id: 'p11', name: 'Éclair Grand Cru', cat: 'signatures', catLabel: 'Signature',
    price: 8, layout: 'tall',
    bg: '#1E1915', mono: 'E',
    desc: 'Pâte à choux, crémeux chocolat Madagascar 75%, glaçage miroir.',
    allergens: 'Gluten · Lait · Œuf',
    origin: 'Madagascar',
    time: '18h',
  },
  {
    id: 'p12', name: 'Vanille', cat: 'signatures', catLabel: 'Signature',
    price: 9, layout: 'normal', tag: 'Saison',
    bg: '#28221A', mono: 'V',
    desc: 'Biscuit joconde, ganache montée vanille Bourbon, caramel mou.',
    allergens: 'Gluten · Lait · Œuf',
    origin: 'Réunion',
    time: '24h',
  },
  {
    id: 'p13', name: 'Pain au Chocolat', cat: 'viennoiseries', catLabel: 'Viennoiserie',
    price: 3.5, layout: 'wide',
    bg: '#1B1713', mono: 'PC',
    desc: 'Feuilletage 72 couches, deux barres chocolat noir 66%.',
    allergens: 'Gluten · Lait · Œuf',
    origin: 'France',
    time: '14h',
  },
  {
    id: 'p14', name: 'Truffe', cat: 'chocolats', catLabel: 'Chocolat',
    price: 6, layout: 'normal',
    bg: '#171411', mono: 'T',
    desc: 'Ganache chocolat noir, cacao en poudre, fleur de sel.',
    allergens: 'Lait',
    origin: 'Venezuela',
    time: '8h',
  },
];

const VALUES = [
  { num: '01', title: 'Local', body: 'Farines de meunerie belge, beurre d\u2019Ardenne, \u0153ufs de poules \u00e9lev\u00e9es au sol.' },
  { num: '02', title: 'Fait main', body: 'Chaque pi\u00e8ce est fa\u00e7onn\u00e9e \u00e0 la main, dans l\u2019atelier, sans aucune pr\u00e9paration industrielle.' },
  { num: '03', title: 'Frais', body: 'Production du jour. Jamais de cong\u00e9lation. Ce qui n\u2019est pas vendu est donn\u00e9.' },
  { num: '04', title: 'Sur commande', body: 'Les \u00e9v\u00e9nements sont pr\u00e9par\u00e9s 48h \u00e0 l\u2019avance pour garantir la fra\u00eecheur.' },
];

const TIME_SLOTS = [
  { day: 'Jeu', time: '10h' },
  { day: 'Jeu', time: '14h' },
  { day: 'Jeu', time: '17h' },
  { day: 'Ven', time: '10h' },
  { day: 'Ven', time: '14h' },
  { day: 'Ven', time: '17h' },
  { day: 'Sam', time: '9h' },
  { day: 'Sam', time: '12h' },
  { day: 'Sam', time: '16h' },
];

window.MaisonData = { CATEGORIES, PRODUCTS, VALUES, TIME_SLOTS };
