services:
  db:
    image: postgres:16
    container_name: patisserie_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: patisserie
      POSTGRES_PASSWORD: Jus_d-OraNgeS
      POSTGRES_DB: patisserie
    ports:
      - "5120:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
